version: '3'
services:  
  rabbitmq:
   build: ../rabbitmq-healthcheck
   ports:
      - "5673:5672"
      - "15673:15672"
   healthcheck:
    test: ["CMD", "docker-health"]
    interval: 10s
    timeout: 10s
    retries: 10
  